### ISSUE TITLE
IllegalArgumentException when `instrument recursively` on case class symbol test-constant

### ISSUE THREAD

**Issue by ikappaki** [jpmonettas/flow-storm-debugger#72]
Hi,

there appears to be an issue when `instrument recursively` on the UI a fn with a [case](https://clojuredocs.org/clojure.core/case) whose test-constant is a parenthesized class symbol, such as `(java.lang.Boolean)`:

`Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: no conversion to symbol`

To reproduce
1. Create an example namespaced fn in `src/issue.clj`
```clj
(ns issue)

(defn t1 [x]
  (case x
    (java.lang.Boolean) (println :abc)))
```
2.  Bring up the REPL
``` powershell 
clj -Sforce -Sdeps '{:deps {com.github.jpmonettas/flow-storm-dbg {:mvn/version """3.3.313"""}}}'
```
3. Bring up flow storm
``` clojure
(do (require '[flow-storm.api :as fs-api]) (fs-api/local-connect))
```
4. load example file
``` clojure
(load-file "src/issue.clj")
```
5. On the flow storm UI, select the `issue/t1` fn and click on the `instrument recursively` button.
![image](https://user-images.githubusercontent.com/34983288/215354864-58dd101d-9f40-42e3-a3cf-b21e4d79b333.png)
6. Nothing changes in the UI, but there is an exception in the REPL:
``` 
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: no conversion to symbol
        at clojure.core$symbol.invokeStatic(core.clj:598)
        at clojure.core$symbol.invoke(core.clj:591)
        at hansel.api$instrument_var_clj$resolve_symb__11713.invoke(api.clj:77)
        at hansel.api$find_interesting_vars_references$fn__11703.invoke(api.clj:36)
        at clojure.core$keep$fn__8649.invoke(core.clj:7409)
   ...
```

Evaluating `(issue/t1 'java.lang.Boolean)` otherwise prints out `:abc` as expected.

REPL output
```
Clojure 1.11.1
user=> (do (require '[flow-storm.api :as fs-api]) (fs-api/local-connect))
[Starting Events queue subsystem]
Events queue started
[Starting Runtime Api subsystem]
[Starting docs subsystem]
Loading docs using () files
[Starting UI subsystem]
Jan 29, 2023 com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @496a023a'
#object[flow_storm.runtime.taps$setup_tap_BANG_$tap_f__10647 0x7d043960 "flow_storm.runtime.taps$setup_tap_BANG_$tap_f__10647@7d043960"]
user=> (load-file "src/issue.clj")
nil
user=> Instrumenting var issue/t1 {:deep? true}
Re-evaluating var: issue/t1 deep?: true instrument?: true
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: no conversion to symbol
        at clojure.core$symbol.invokeStatic(core.clj:598)
        at clojure.core$symbol.invoke(core.clj:591)
        at hansel.api$instrument_var_clj$resolve_symb__11713.invoke(api.clj:77)
        at hansel.api$find_interesting_vars_references$fn__11703.invoke(api.clj:36)
        at clojure.core$keep$fn__8649.invoke(core.clj:7409)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$filter$fn__5962.invoke(core.clj:2826)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.lang.RT.countFrom(RT.java:650)
        at clojure.lang.RT.count(RT.java:643)
        at hansel.api$instrument_var_clj.invokeStatic(api.clj:80)
        at hansel.api$instrument_var_clj.invoke(api.clj:39)
        at hansel.api$instrument_var_clj.invokeStatic(api.clj:48)
        at hansel.api$instrument_var_clj.invoke(api.clj:39)
        at flow_storm.runtime.debuggers_api$instrument_var.invokeStatic(debuggers_api.cljc:162)
        at flow_storm.runtime.debuggers_api$instrument_var.invoke(debuggers_api.cljc:155)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at flow_storm.debugger.runtime_api$api_call.invokeStatic(runtime_api.clj:99)
        at flow_storm.debugger.runtime_api$api_call.invoke(runtime_api.clj:83)
        at flow_storm.debugger.runtime_api$api_call.invokeStatic(runtime_api.clj:84)
        at flow_storm.debugger.runtime_api$api_call.invoke(runtime_api.clj:83)
        at flow_storm.debugger.runtime_api.LocalRuntimeApi.instrument_var(runtime_api.clj:129)
        at flow_storm.debugger.ui.browser.screen$instrument_function.invokeStatic(screen.clj:52)
        at flow_storm.debugger.ui.browser.screen$instrument_function.invoke(screen.clj:47)
        at flow_storm.debugger.ui.browser.screen$update_selected_fn_detail_pane$event_handler_fn__15398.invoke(screen.clj:95)
        at flow_storm.debugger.ui.utils$event_handler_STAR_$reify__12594.handle(utils.clj:45)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8797)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:833)

user=> (issue/t1 'java.lang.Boolean)
:abc
nil
user=>
```

Thanks

**Comment by jpmonettas** [comment]
Thanks again for reporting this!

Fixed in Hansel https://github.com/jpmonettas/hansel/commit/b53bf83776639e99c3108a542a800f1a55ebcc4c

FlowStorm master is currently using Hansel 0.1.42 which contains the fix
