### ISSUE TITLE
clojure-storm not working with tick

### ISSUE THREAD

**Issue by dakra** [jpmonettas/flow-storm-debugger#82]
If I add the tick dependency while using clojure-storm I get an exception.

Repro:

Use the clj command from the getting-started docs but add tick/tick dep:
```
clj -Sforce -Sdeps '{:deps {} :aliases {:dev {:classpath-overrides {org.clojure/clojure nil} :extra-deps {com.github.jpmonettas/clojure {:mvn/version "RELEASE"} com.github.jpmonettas/flow-storm-dbg {:mvn/version "RELEASE"} tick/tick {:mvn/version "0.6.2"}} :jvm-opts ["-Dclojure.storm.instrumentEnable=true" "-Dclojure.storm.instrumentOnlyPrefixes=user"]}}}' -A:dev
```
and require tick to get an exception:
```
user=> (require '[tick.core])
Error in thread Thread[#1,main,5,main]
Syntax error macroexpanding at (cljc/java_time/year.clj:10:1).
        at clojure.lang.Compiler.load(Compiler.java:7890)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6958.invoke(core.clj:6167)
        at clojure.core$load.invokeStatic(core.clj:6166)
        at clojure.core$load.doInvoke(core.clj:6150)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at clojure.core$load_one.invokeStatic(core.clj:5939)
        at clojure.core$load_one.invoke(core.clj:5934)
        at clojure.core$load_lib$fn__6900.invoke(core.clj:5981)
        at clojure.core$load_lib.invokeStatic(core.clj:5980)
        at clojure.core$load_lib.doInvoke(core.clj:5959)
        at clojure.lang.RestFn.applyTo(RestFn.java:145)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6022)
        at clojure.core$load_libs.doInvoke(core.clj:6006)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6044)
        at clojure.core$require.doInvoke(core.clj:6044)
        at clojure.lang.RestFn.invoke(RestFn.java:3897)
        at tick.core$eval173$loading__6839__auto____174.invoke(core.cljc:3)
        at tick.core$eval173.invokeStatic(core.cljc:3)
        at tick.core$eval173.invoke(core.cljc:3)
        at clojure.lang.Compiler.eval(Compiler.java:7410)
        at clojure.lang.Compiler.eval(Compiler.java:7399)
        at clojure.lang.Compiler.load(Compiler.java:7876)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6958.invoke(core.clj:6167)
        at clojure.core$load.invokeStatic(core.clj:6166)
        at clojure.core$load.doInvoke(core.clj:6150)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at clojure.core$load_one.invokeStatic(core.clj:5939)
        at clojure.core$load_one.invoke(core.clj:5934)
        at clojure.core$load_lib$fn__6900.invoke(core.clj:5981)
        at clojure.core$load_lib.invokeStatic(core.clj:5980)
        at clojure.core$load_lib.doInvoke(core.clj:5959)
        at clojure.lang.RestFn.applyTo(RestFn.java:145)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6022)
        at clojure.core$load_libs.doInvoke(core.clj:6006)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6044)
        at clojure.core$require.doInvoke(core.clj:6044)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at user$eval167.invokeStatic(NO_SOURCE_FILE:1)
        at user$eval167.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:7410)
        at clojure.lang.Compiler.eval(Compiler.java:7334)
        at clojure.core$eval.invokeStatic(core.clj:3221)
        at clojure.core$eval.invoke(core.clj:3217)
        at clojure.main$repl$read_eval_print__9285$fn__9288.invoke(main.clj:447)
        at clojure.main$repl$read_eval_print__9285.invoke(main.clj:447)
        at clojure.main$repl$fn__9295.invoke(main.clj:469)
        at clojure.main$repl.invokeStatic(main.clj:469)
        at clojure.main$repl_opt.invokeStatic(main.clj:533)
        at clojure.main$main.invokeStatic(main.clj:679)
        at clojure.main$main.doInvoke(main.clj:628)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:135)
        at clojure.lang.Var.applyTo(Var.java:707)
        at clojure.main.main(main.java:40)
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
        at clojure.lang.Compiler.eval(Compiler.java:7379)
        at clojure.lang.Compiler.load(Compiler.java:7876)
        ... 68 more
Execution error (ClassCastException) at tick.core/eval173$loading (core.cljc:3).
class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
```

It works when I remove the clojure-storm dependency and only use flow-storm plus normal clojure.

Thanks for this great tool :)

**Comment by jpmonettas** [comment]
Oh damn, I'll take a look!

Thanks for reporting the minimal repro case  @dakra !

**Comment by jpmonettas** [comment]
Ok, this is fixed in https://github.com/jpmonettas/clojure/commit/1c4cb29856c6f7bd589bdf7212bb3de026d3feb4 and released in

ClojureStorm  "1.11.1-5" and "1.12.0-alpha3_3"

The problem was that for registering forms it assumed :line info always comes from the LispReader and is an int, but as you can see in the cljc.java-time (dragged by tick) library https://github.com/henryw374/cljc.java-time/blob/master/src/cljc/java_time/year.clj#L10 sometimes the :line meta is specified as a Long.

**Comment by dakra** [comment]
That was fast. Thank you very much!
