### ISSUE TITLE
Error when evaling #trace "form" is null

### ISSUE THREAD

**Issue by benjamin-asdf** [jpmonettas/flow-storm-debugger#92]
Hi

I am trying this 

deps.edn
```clojure
{:aliases
 {:flowstorm
  {:classpath-overrides {org.clojure/clojure nil}
   :extra-deps {com.github.jpmonettas/clojure {:mvn/version "1.11.1-8"}
                com.github.jpmonettas/flow-storm-dbg {:mvn/version "3.7.0"}}
   :jvm-opts ["-Dclojure.storm.instrumentEnable=true"
              "-Dclojure.storm.instrumentOnlyPrefixes=user"]}}}
```              

start with cider (+flowstorm alias) jack-in

```
(ns hello)

(comment
  (require '[flow-storm.api :as fs-api])
  (fs-api/local-connect {:style "~/flowstorm/styles.css"})

  #trace
  (defn sum [a b]
    (+ a b))

;; Error in thread Thread[#35,nREPL-session-f6e300d1-f877-466c-ad35-99207dc5f556,5,main]
;; java.lang.NullPointerException: Cannot invoke "clojure.storm.IForm.getForm()" because "form" is null
;; 	at clojure.storm.FormRegistry.makeFormMap(FormRegistry.java:27)
;; 	at clojure.storm.FormRegistry.getForm(FormRegistry.java:57)
;; 	at flow_storm.runtime.indexes.storm_form_registry.StormFormRegistry.get_form(storm_form_registry.clj:13)
;; 	at flow_storm.runtime.indexes.api$get_form.invokeStatic(api.cljc:196)
;; 	at flow_storm.runtime.indexes.api$get_form.invoke(api.cljc:194)
;; 	at flow_storm.tracer$trace_form_init.invokeStatic(tracer.cljc:99)
;; 	at flow_storm.tracer$trace_form_init.invoke(tracer.cljc:92)
;; 	at hello$eval10516.invokeStatic(NO_SOURCE_FILE:0)
;; 	at hello$eval10516.invoke(NO_SOURCE_FILE)
;; 	at clojure.lang.Compiler.eval(Compiler.java:7430)
;; 	at clojure.lang.Compiler.eval(Compiler.java:7419)
;; 	at clojure.lang.Compiler.eval(Compiler.java:7350)
;; 	at clojure.core$eval.invokeStatic(core.clj:3215)
;; 	at clojure.core$eval.invoke(core.clj:3211)
;; 	at nrepl.middleware.interruptible_eval$evaluate$fn__1269$fn__1270.invoke(interruptible_eval.clj:87)
;; 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
;; 	at clojure.lang.AFn.applyTo(AFn.java:144)
;; 	at clojure.core$apply.invokeStatic(core.clj:667)
;; 	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
;; 	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
;; 	at clojure.lang.RestFn.invoke(RestFn.java:425)
;; 	at nrepl.middleware.interruptible_eval$evaluate$fn__1269.invoke(interruptible_eval.clj:87)
;; 	at clojure.main$repl$read_eval_print__9247$fn__9250.invoke(main.clj:445)
;; 	at clojure.main$repl$read_eval_print__9247.invoke(main.clj:445)
;; 	at clojure.main$repl$fn__9257.invoke(main.clj:467)
;; 	at clojure.main$repl.invokeStatic(main.clj:467)
;; 	at clojure.main$repl.doInvoke(main.clj:369)
;; 	at clojure.lang.RestFn.invoke(RestFn.java:1523)
;; 	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
;; 	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
;; 	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__1302$fn__1306.invoke(interruptible_eval.clj:152)
;; 	at clojure.lang.AFn.run(AFn.java:22)
;; 	at nrepl.middleware.session$session_exec$main_loop__1372$fn__1376.invoke(session.clj:218)
;; 	at nrepl.middleware.session$session_exec$main_loop__1372.invoke(session.clj:217)
;; 	at clojure.lang.AFn.run(AFn.java:22)
;; 	at java.base/java.lang.Thread.run(Thread.java:1623)
  )
```

**Comment by jpmonettas** [comment]
Hi! You don't need to require anything or use `#trace` when using FlowStorm with ClojureStorm. ClojureStorm gives you automatic instrumentation.

What you want is :
```clojure
{:aliases
 {:flowstorm
  {:classpath-overrides {org.clojure/clojure nil}
   :extra-deps {com.github.jpmonettas/clojure {:mvn/version "1.11.1-8"}
                com.github.jpmonettas/flow-storm-dbg {:mvn/version "3.7.0"}}
   :jvm-opts ["-Dclojure.storm.instrumentEnable=true"
              "-Dclojure.storm.instrumentOnlyPrefixes=hello"]}}} ;; <==== specify here all the ns you want to be automatically instrumented, this will normally be your base project namespace
```
So if you have namespace like `my-project.core`, `my-project.db`, `my-project.db.utils` etc you can do  `"-Dclojure.storm.instrumentOnlyPrefixes=my-project"` and everything will be automatically instrumented.

Then you start your repl, and whenever you need the UI just eval the `:dbg` keyword at the repl and just run stuff, no need to add or require anything.
